### ISSUE TITLE
Implement recommended community standards for CMEW

### ISSUE THREAD

**Issue by ehogan** [MetOffice/CMEW#83]
Implement recomended community standards for CMEW, see, for example, [ESMValTool Community Standards](https://github.com/ESMValGroup/ESMValTool/community).

### Review of community files (based on [ESMValTool Community Standards](https://github.com/ESMValGroup/ESMValTool/community))

Note: checkboxes below are ticked if no work is needed or if there is an issue open for the work.

- [x] **Description:** I believe the description is the text under "About" title on the top right of https://github.com/MetOffice/CMEW. This text matches with what is already in the `Introduction` section of the [README.md](https://github.com/MetOffice/CMEW/blob/main/README.md) file, so no work is needed.
- [x] **README:** CMEW already has a [README.md](https://github.com/MetOffice/CMEW/blob/main/README.md) file, so no work is needed.
- [x] **Code of conduct:** see #193.
- [x] **Contributing guidelines:** see #194.
- [x] **License:** see #183.
- [x] **Security policy:** see #197.
- [x] **Issue templates:** see #198.
- [x] **Pull request template:** CMEW already has a [pull request template](https://github.com/MetOffice/CMEW/blob/main/.github/pull_request_template.md), so no work is needed.
- [x] **Repository admins accept content reports:** #200.

Additionally, from [GitHub Docs: Creating a default community health file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types):

- [x] **Support:** see #199.

**Details**

- Useful link: [GitHub Docs: About community profiles for public repositories](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/about-community-profiles-for-public-repositories).
